<?php $currentUrl = Mage::helper('core/url')->getCurrentUrl();
$url = Mage::getSingleton('core/url')->parseUrl($currentUrl);
$path = $url->getPath();
$pathTest = array('/wholesalecanada/order.html');
$store = Mage::app()->getStore()->getCode();
if(in_array($path, $pathTest) && $store=='wholesalecanada'):?>

<?php
    $_productCollection= Mage::getModel('catalog/product')->getCollection()->addWebsiteFilter()->addMinimalPrice() ;
    $_productCollection->addAttributeToSelect('*');
    $_productCollection->setOrder('sku', 'asc')->load();
    $_helper = $this->helper('catalog/output');
?>

<?php if(!$_productCollection->count()): ?>
	<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
	<div class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <form id="checkall-form" action="<?php echo $this->getUrl('checkout/cart/multiaddtocart') ?>" method="post">
    <input type="checkbox" value="1" class="checkall" name="checkall">
    <label for="checkall">Check All</label>
    <button class="button btn-cartall" title="Add to Cart" type="button">
    <span><span>Add to Cart</span></span>
    </button>
    <?php $_iterator = 0; ?>
    <table width="100%" cellspacing="0" cellpadding="0" border="0" class="data-table" id="products-list">
    <ol class="products-list" id="products-list">
	<tr>
		<td></td>
		<td>SKU</td>
		<td>Name</td>
		<td>Price</td>
		<td>Quantity</td>
	</tr>
    <?php foreach ($_productCollection as $_product): ?>
	<tr>
        <?php if( ++$_iterator == sizeof($_productCollection) ): ?> <?php endif; ?>

            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
                    <div class="product-primary">
			<td>
                        <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
                            <p class="action">
                            <input type="checkbox" value="<?php echo $_product->getId() ?>" id="check-<?php echo $_product->getId() ?>" class="check" name="check[]">
			<?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
                            <p class="action"><a title="<?php echo $this->quoteEscape($this->__('View Details')) ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a></p>
                        <?php else: ?>
                            <p class="action availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                            </p>
			</td>
			<td><?php $sku = $_product->getData('sku'); echo $sku?></td>
			<td>
                        <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                        <?php
                        // Provides extra blocks on which to hang some features for products in the list
                        // Features providing UI elements targeting this block will display directly below the product name
                        if ($this->getChild('name.after')) {
                            $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                            foreach ($_nameAfterChildren as $_nameAfterChildName) {
                                $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                $_nameAfterChild->setProduct($_product);
                                echo $_nameAfterChild->toHtml();
                            }
                        }
                        ?>
			</td>
                    </div>
			<td>
                    <div class="product-secondary">

                        <?php echo $this->getPriceHtml($_product, true) ?>
			<?php echo $_product ?>
                    </div>
			</td>
                    <div class="product-secondary">
			<td>
                        <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
                            <p class="action">
				<?php $productQuantity = Mage::getModel("cataloginventory/stock_item")
->loadByProduct($_product->getId()); ?>
                            <input type="text" style="width: 50px;" value="<?php echo $productQuantity->getMinSaleQty() ?>" id="qty-<?php echo $_product->getId() ?>" name="qty_<?php echo $_product->getId() ?>" class="quantity">
                            </p>
                        <?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
                            <p class="action"><a title="<?php echo $this->quoteEscape($this->__('View Details')) ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a></p>
                        <?php else: ?>
                            <p class="action availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
			</td>
                    </div>
                </div>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    </tr>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
</table>
<?php endif; ?>

<?php else: ?>
<?php
$_productCollection=$this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
// common variable
$id_rand = rand();
$theme_helper = $this->helper('sebian');
$quick_view	= $theme_helper->getCfg('quick_view_product/enableview') ? true : false;
$aspect_ratio = ($theme_helper->getCfg('category/aspect_ratio')) ? true : false;
$image_options = ($image_options = $theme_helper->getCfg('category/image_options')) ? $image_options : 'none';
$image_options_slideshow_item = ($image_options_slideshow_item = $theme_helper->getCfg('category/slideshow_item')) ? $image_options_slideshow_item : 4;

$second_image_column = ($second_image_column = $theme_helper->getCfg('category/alt_image_column')) ? $second_image_column : 'position';
$second_image_column_value = ($second_image_column_value = $theme_helper->getCfg('category/alt_image_column_value')) ? $second_image_column_value : '1';
$image_width = ($image_width = $theme_helper->getCfg('category/image_width')) ? $image_width : 270;
$image_height = ($image_height = $theme_helper->getCfg('category/image_height')) ? $image_height : 340;
$second_image_effect = ($second_image_effect = $theme_helper->getCfg('category/alt_image_effect')) ? $second_image_effect : 'transform';
$class_item_effect = '';
$second_image_effect_tmp = explode('_',$second_image_effect);
foreach($second_image_effect_tmp as $cl){
    $class_item_effect .= " {$cl}-effect";
}
$class_item_effect_2 = $class_item_effect;
$g_columns = ($g_columns = $theme_helper->getCfg('category_grid/column_count')) ? $g_columns : 4;

$grid_style = $theme_helper->getCfg('category_grid/style') ? $theme_helper->getCfg('category_grid/style') : 'style_1';

$show_countdown = $theme_helper->getCfg('product_countdown/catalog') ? true : false ;
?>
<?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="category-products">
        <?php echo $this->getToolbarHtml() ?>
        <?php // List mode ?>
        <?php if($this->getMode()!='grid'): ?>
            <?php $_iterator = 0; ?>
            <ol class="products-list" id="product-list-<?php echo $id_rand;?>" style="padding-left:0;">
                <?php foreach ($_productCollection as $_product): ?>
                    <?php
                    $_tpl_image = '<a class="product-image" href="%s" title="%s">%s<div class="image-overlay"></div></a>';
                    if($image_options == 'slideshow'){
                        $_tpl_image = '<div class="product-image product-image-slideshow"><div class="wrapper-slideshow"><div class="image-overlay"></div><a href="%s" title="%s">%s</a></div></div>';
                    }
                    $_front_image = '<img class="front product-collection-image" src="'.$this->helper('catalog/image')
                            ->init($_product, 'small_image')
                            ->keepAspectRatio($aspect_ratio)
                            ->resize($image_width,$image_height) .'"
                        alt="'.$this->stripTags($_product->getName(), null, true).'" />';
                    $_back_image = '';
                    if($image_options == 'alt_image' || $image_options == 'slideshow'){
                        $product        =   Mage::getModel('catalog/product')->load($_product->getId());
                        $mediaGallery   =   $product->getMediaGalleryImages();
                        if($image_options == 'alt_image'){
                            $filterMediaGallery=$mediaGallery->getItemsByColumnValue($second_image_column,$second_image_column_value);
                            if(count($filterMediaGallery) > 0){
                                foreach ($filterMediaGallery as $singleMediaGallery) {
                                    $file = $singleMediaGallery->getFile();
                                    $_back_image = '<img class="back" src="'.$this->helper('catalog/image')
                                            ->init($product, 'small_image', $file)
                                            ->keepAspectRatio($aspect_ratio)
                                            ->resize($image_width,$image_height).'"
                                        alt="'.$this->stripTags($product->getName(), null, true).'"/>';
                                }
                            }
                        }
                        if($image_options == 'slideshow'){
                            $class_item_effect = '';
                            if($product->getImage() == 'no_selection' && count($galleryImages) == 0){
                                $_back_image = '';
                                $_tpl_image = '<a class="product-image" href="%s" title="%s"><div class="image-overlay"></div>%s</a>';
                            }else{
                                $i_counter = 0;
                                foreach ($mediaGallery as $_gallery_item){
                                    if($i_counter == 0){
                                        $_front_image = '<img class="product-collection-image thumbnail-item" src="'.$this->helper('catalog/image')
                                                ->init($product, 'small_image', $_gallery_item->getFile())
                                                ->keepAspectRatio($aspect_ratio)
                                                ->resize($image_width,$image_height).'"
                                            alt="'.$this->stripTags($product->getName(), null, true).'" />';
                                    }else{
                                        $_back_image .= '<img class="thumbnail-item hidden-slowly" src="'.$this->helper('catalog/image')
                                                ->init($product, 'small_image', $_gallery_item->getFile())
                                                ->keepAspectRatio($aspect_ratio)
                                                ->resize($image_width,$image_height).'"
                                            alt="'.$this->stripTags($product->getName(), null, true).'" />';
                                    }
                                    if($image_options_slideshow_item == $i_counter++) break;
                                }
                            }
                        }
                    }
                    if($_back_image == ''){
                        $class_item_effect = '';
                    }
                    ?>
                    <li class="item">
                        <input type="hidden" value="<?php echo $_product->getId()?>" name="product"/>
                        <div class="inner-item">
                            <div class="outer-image<?php echo $class_item_effect;?>">
                                <?php if($show_countdown){
                                    echo $theme_helper->show_product_countdown($_product);
                                }?>
                                <?php echo $theme_helper->getLabel($_product);?>
                                <?php echo sprintf(
                                    $_tpl_image,
                                    $_product->getProductUrl(),
                                    $this->stripTags($_product->getName(), null, true),
                                    $_front_image . $_back_image
                                );?>
                                <?php if($quick_view):?><a data-toggle="tooltip" href="<?php echo $this->getUrl('arexworks/quickview/index',array('product_id'=>$_product->getId()));?>" class="button link-quickview" title="<?php echo $this->__('Quick View') ?>"><span class="fa fa-search"></span></a><?php endif;?>
                            </div>
                            <div class="product-shop">
                                <div class="f-fix">
                                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><span><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></span></a></h2>
                                    <?php
                                    if ($this->getChild('name.after')) {
                                        $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                                        foreach ($_nameAfterChildren as $_nameAfterChildName) {
                                            $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                            $_nameAfterChild->setProduct($_product);
                                            echo $_nameAfterChild->toHtml();
                                        }
                                    }
                                    ?>
                                    <?php echo $this->getPriceHtml($_product, true ,'-list') ?>
				    
                                    <div class="desc std">
                                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    </div>
                                    <?php if($_product->isSaleable()): ?>
                                    <?php else: ?>
                                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                    <?php endif; ?>
                                    <div class="actions">
                                        <div class="add-to-box clearfix">
                                            <div class="link-actions" style="padding-left:2em;">
                                                <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?><a data-toggle="tooltip" href="<?php echo $_compareUrl ?>" class="button link-compare" style="border-color:#fff;" title="<?php echo $this->__('Add to Compare') ?>"><span class="fa fa-check"></span></a><?php endif; ?>
                                                <?php if ($this->helper('wishlist')->isAllow()) : ?><a data-toggle="tooltip" href="<?php echo $this->getAddToWishlistUrl($_product) ?>" class="button link-wishlist" style="border-color:#fff;" title="<?php echo $this->__('Add to Wishlist') ?>"><span class="fa fa-heart-o"></span></a><?php endif; ?>
                                            </div>
                                            <?php if($_product->isSaleable()): ?>
                                                <button onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')" class="button btn-cart" title="<?php echo $this->__('Add to Cart') ?>"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                            <?php else: ?>
                                                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                    <?php $class_item_effect = $class_item_effect_2;?>
                <?php endforeach; ?>
            </ol>
        <?php else: ?>
            <?php // Grid Mode ?>
            <?php
            $_collectionSize = $_productCollection->count();
            $this->setColumnCount($g_columns);
            $_columnCount = $this->getColumnCount();
            ?>
            <ul class="products-grid arw-<?php echo $_columnCount;?>-col arw-row" id="product-list-<?php echo $id_rand;?>">
                <?php $i=0; foreach ($_productCollection as $_product): ?>
                    <?php
                    $_tpl_image = '<a class="product-image" href="%s" title="%s">%s<div class="image-overlay"></div></a>';
                    if($image_options == 'slideshow'){
                        $_tpl_image = '<div class="product-image product-image-slideshow"><div class="wrapper-slideshow"><div class="image-overlay"></div><a href="%s" title="%s">%s</a></div></div>';
                    }
                    $_front_image = '<img class="front product-collection-image" src="'.$this->helper('catalog/image')
                            ->init($_product, 'small_image')
                            ->keepAspectRatio($aspect_ratio)
                            ->resize($image_width,$image_height) .'"
                        alt="'.$this->stripTags($_product->getName(), null, true).'" />';
                    $_back_image = '';
                    if($image_options == 'alt_image' || $image_options == 'slideshow'){
                        $product        =   Mage::getModel('catalog/product')->load($_product->getId());
                        $mediaGallery   =   $product->getMediaGalleryImages();
                        if($image_options == 'alt_image'){
                            $filterMediaGallery=$mediaGallery->getItemsByColumnValue($second_image_column,$second_image_column_value);
                            if(count($filterMediaGallery) > 0){
                                foreach ($filterMediaGallery as $singleMediaGallery) {
                                    $file = $singleMediaGallery->getFile();
                                    $_back_image = '<img class="back" src="'.$this->helper('catalog/image')
                                            ->init($product, 'small_image', $file)
                                            ->keepAspectRatio($aspect_ratio)
                                            ->resize($image_width,$image_height).'"
                                        alt="'.$this->stripTags($product->getName(), null, true).'"/>';
                                }
                            }
                        }
                        if($image_options == 'slideshow'){
                            $class_item_effect = '';
                            if($product->getImage() == 'no_selection' && count($galleryImages) == 0){
                                $_back_image = '';
                                $_tpl_image = '<a class="product-image" href="%s" title="%s"><div class="image-overlay"></div>%s</a>';
                            }else{
                                $i_counter = 0;
                                foreach ($mediaGallery as $_gallery_item){
                                    if($i_counter == 0){
                                        $_front_image = '<img class="product-collection-image thumbnail-item" src="'.$this->helper('catalog/image')
                                                ->init($product, 'small_image', $_gallery_item->getFile())
                                                ->keepAspectRatio($aspect_ratio)
                                                ->resize($image_width,$image_height).'"
                                            alt="'.$this->stripTags($product->getName(), null, true).'" />';
                                    }else{
                                        $_back_image .= '<img class="thumbnail-item hidden-slowly" src="'.$this->helper('catalog/image')
                                                ->init($product, 'small_image', $_gallery_item->getFile())
                                                ->keepAspectRatio($aspect_ratio)
                                                ->resize($image_width,$image_height).'"
                                            alt="'.$this->stripTags($product->getName(), null, true).'" />';
                                    }
                                    if($image_options_slideshow_item == $i_counter++) break;
                                }
                            }
                        }
                    }
                    if($_back_image == ''){
                        $class_item_effect = '';
                    }
                    ?>
                    <li class="arw-col item">
                        <div class="wrapper-item">
                            <?php echo $theme_helper->getLabel($_product);?>
                            <input type="hidden" value="<?php echo $_product->getId()?>" name="product"/>
                            <div class="wrapper-item-inner <?php echo $class_item_effect;?>">
                                <div class="outer-image">
                                    <?php echo sprintf(
                                        $_tpl_image,
                                        $_product->getProductUrl(),
                                        $this->stripTags($_product->getName(), null, true),
                                        $_front_image . $_back_image
                                    );?>
                                </div>
                                <?php if($grid_style == 'style_1'):?>
                                    <div class="actions">
                                        <div class="link-actions">
                                            <?php if($quick_view):?><a data-toggle="tooltip" href="<?php echo $this->getUrl('arexworks/quickview/index',array('product_id'=>$_product->getId()));?>" class="button link-quickview" title="<?php echo $this->__('Quick View') ?>"><span class="fa fa-search"></span></a><?php endif;?><?php /*
        */?><?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?><a data-toggle="tooltip" href="<?php echo $_compareUrl ?>" class="button link-compare" title="<?php echo $this->__('Add to Compare') ?>"><span class="fa fa-check"></span></a><?php endif; ?><?php /*
        */?><?php if ($this->helper('wishlist')->isAllow()) : ?><a data-toggle="tooltip" href="<?php echo $this->getAddToWishlistUrl($_product) ?>" class="button link-wishlist" title="<?php echo $this->__('Add to Wishlist') ?>"><span class="fa fa-heart-o"></span></a><?php endif; ?>
                                        </div>
                                        <?php if($_product->isSaleable()): ?>
                                            <button onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')" class="button btn-cart" title="<?php echo $this->__('Add to Cart') ?>"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                        <?php else: ?>
                                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                        <?php endif; ?>
                                    </div>
                                <?php endif;?>
                                <?php if($grid_style == 'style_2'):?>
                                    <?php if($quick_view):?><a data-toggle="tooltip" href="<?php echo $this->getUrl('arexworks/quickview/index',array('product_id'=>$_product->getId()));?>" class="button link-quickview" title="<?php echo $this->__('Quick View') ?>"><span class="fa fa-search"></span></a><?php endif;?>
                                    <div class="product-info">
                                        <div class="link-actions-2">
                                            <?php if($_product->isSaleable()): ?><a data-toggle="tooltip" href="<?php echo $this->getAddToCartUrl($_product) ?>" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')" class="button btn-cart" title="<?php echo $this->__('Add to Cart') ?>"><span class="fa fa-shopping-cart"></span></span></a><?php endif;?><?php /*
                */?><?php if ($this->helper('wishlist')->isAllow()) : ?><a data-toggle="tooltip" href="<?php echo $this->getAddToWishlistUrl($_product) ?>" class="button link-wishlist" title="<?php echo $this->__('Add to Wishlist') ?>"><span class="fa fa-heart-o"></span></a><?php endif; ?><?php /*
                */?><?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?><a data-toggle="tooltip" href="<?php echo $_compareUrl ?>" class="button link-compare" title="<?php echo $this->__('Add to Compare') ?>"><span class="fa fa-check"></span></a><?php endif; ?>
                                        </div>
                                        <?php
                                        if ($this->getChild('name.after')) {
                                            $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                                            foreach ($_nameAfterChildren as $_nameAfterChildName) {
                                                $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                                $_nameAfterChild->setProduct($_product);
                                                echo $_nameAfterChild->toHtml();
                                            }
                                        }
                                        ?>
                                        <h2 class="product-name">
                                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                                                <span><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></span>
                                            </a>
                                        </h2>
                                        <?php echo $this->getPriceHtml($_product, true ,'-list') ?>
                                    </div>
                                <?php endif;?>
                            </div>
                            <?php if($grid_style == 'style_1'):?>
                                <div class="product-info">
                                    <?php
                                    if ($this->getChild('name.after')) {
                                        $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                                        foreach ($_nameAfterChildren as $_nameAfterChildName) {
                                            $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                            $_nameAfterChild->setProduct($_product);
                                            echo $_nameAfterChild->toHtml();
                                        }
                                    }
                                    ?>
                                    <h2 class="product-name">
                                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                                            <span><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></span>
                                        </a>
						<span style="color:#b8b8b8;"><?php echo $_product->getAttributeText('volume') ?></span>
                                    </h2>
                                    <?php echo $this->getPriceHtml($_product, true ,'-list') ?>
				  </div>
                            <?php endif;?>
                        </div>
                    </li>
                    <?php $class_item_effect = $class_item_effect_2;?>
                <?php endforeach ?>
            </ul>
        <?php endif; ?>
        <div class="toolbar-bottom">
            <?php echo $this->getToolbarHtml() ?>
        </div>
        <script type="text/javascript">
            jQuery(document).ready(function(){
                arexworks.Frontend.initOwlGalleryImage(jQuery('#product-list-<?php echo $id_rand;?> .product-image.product-image-slideshow .wrapper-slideshow'));
                <?php foreach ($theme_helper->getProductImageFallbacks($_productCollection,$aspect_ratio,array('list_image','grid_image')) as $imageFallback): ?>
                ConfigurableMediaImages.setImageFallback(<?php echo $imageFallback['product']->getId(); ?>, jQuery.parseJSON('<?php echo $imageFallback['image_fallback']; ?>'));
                <?php endforeach; ?>
                jQuery(document).trigger('configurable-media-images-init');
            });
        </script>
    </div>
<?php endif; ?>
<?php endif; ?>
