<?php $currentUrl = Mage::helper('core/url')->getCurrentUrl();
$url = Mage::getSingleton('core/url')->parseUrl($currentUrl);
$path = $url->getPath();
$pathTest = array('/wholesalecanada/order.html');
$store = Mage::app()->getStore()->getCode();
if(in_array($path, $pathTest) && $store=='wholesalecanada'):?>

<?php
    $_productCollection= Mage::getModel('catalog/product')->getCollection()->addWebsiteFilter()->addMinimalPrice() ;
    $_productCollection->addAttributeToSelect('*');
    $_productCollection->setOrder('sku', 'asc')->load();
    $_helper = $this->helper('catalog/output');
?>

<?php if(!$_productCollection->count()): ?>
	<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
	<div class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <form id="checkall-form" action="<?php echo $this->getUrl('checkout/cart/multiaddtocart') ?>" method="post">
    <input type="checkbox" value="1" class="checkall" name="checkall">
    <label for="checkall">Check All</label>
    <button class="button btn-cartall" title="Add to Cart" type="button">
    <span><span>Add to Cart</span></span>
    </button>
    <?php $_iterator = 0; ?>
    <table width="100%" cellspacing="0" cellpadding="0" border="0" class="data-table" id="products-list">
    <ol class="products-list" id="products-list">
	<tr>
		<td></td>
		<td>SKU</td>
		<td>Name</td>
		<td>Price</td>
		<td>Quantity</td>
	</tr>
    <?php foreach ($_productCollection as $_product): ?>
	<tr>
        <?php if( ++$_iterator == sizeof($_productCollection) ): ?> <?php endif; ?>

            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
                    <div class="product-primary">
			<td>
                        <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
                            <p class="action">
                            <input type="checkbox" value="<?php echo $_product->getId() ?>" id="check-<?php echo $_product->getId() ?>" class="check" name="check[]">
			<?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
                            <p class="action"><a title="<?php echo $this->quoteEscape($this->__('View Details')) ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a></p>
                        <?php else: ?>
                            <p class="action availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                            </p>
			</td>
			<td><?php $sku = $_product->getData('sku'); echo $sku?></td>
			<td>
                        <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                        <?php
                        // Provides extra blocks on which to hang some features for products in the list
                        // Features providing UI elements targeting this block will display directly below the product name
                        if ($this->getChild('name.after')) {
                            $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                            foreach ($_nameAfterChildren as $_nameAfterChildName) {
                                $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                $_nameAfterChild->setProduct($_product);
                                echo $_nameAfterChild->toHtml();
                            }
                        }
                        ?>
			</td>
                    </div>
			<td>
                    <div class="product-secondary">

                        <?php echo $this->getPriceHtml($_product, true) ?>
			<?php echo $_product ?>
                    </div>
			</td>
                    <div class="product-secondary">
			<td>
                        <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
                            <p class="action">
				<?php $productQuantity = Mage::getModel("cataloginventory/stock_item")
->loadByProduct($_product->getId()); ?>
                            <input type="text" style="width: 50px;" value="<?php echo $productQuantity->getMinSaleQty() ?>" id="qty-<?php echo $_product->getId() ?>" name="qty_<?php echo $_product->getId() ?>" class="quantity">
                            </p>
                        <?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
                            <p class="action"><a title="<?php echo $this->quoteEscape($this->__('View Details')) ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a></p>
                        <?php else: ?>
                            <p class="action availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
			</td>
                    </div>
                </div>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    </tr>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
</table>
<?php endif; ?>
<?php endif; ?>
