<!DOCTYPE html>
<html>
  <head>
    <style type="text/css">
      #frame_body { height: 500px; width:700px; margin: 0; padding: 0; }  
      iframe { height: 500px; width:700px; margin: 0; padding: 0; }
    </style>
  </head>
  <body id="frame_body">
    <?php 
    $base_url = Mage::app()->getStore()->isCurrentlySecure() ? Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, true) : Mage::getBaseUrl();
    ?>  
    <iframe src="<?php echo $base_url; ?>canpost/gmap/office" seamless="seamless" width="704" height="502"></iframe>
  </body>
</html>

