<?php

if (Mage::getStoreConfig('news/news_general/enabled') == 1):
    $cid = $this->getRequest()->getParam('cid');
    $i = 0;
   
    $collection = $this->getCategory();
    $count = count($collection);
    if ($count !== 0):
        ?>

        <div class="block block-poll news-extra-block ">
            <div class="block-title">
                <strong><span><?php echo $this->__('Categories');?></span></strong>
                
            </div>
            <div class="block-content">
                
                <ul class="news-list">
                    <?php foreach ($collection as $category_item): 
                        if($category_item['status'] == 1) { 
                        ?>
                        <li<?php if($cid == $category_item['category_id']) { echo ' class="active"'; }?>>
                            <label> <a href="<?php echo $this->getUrl('news/index').'?cid='.$category_item['category_id']; ?>">
                                <?php echo $category_item['name'].'  ('.$this->getCategorisedNews($category_item['category_id']).')'; ?></a></label>
                        </li>
                    <?php 
                        }
                    endforeach; ?> 
                </ul>
                 <div class="actions" >
                    <a href="<?php echo $this->getUrl('news/index') ?>" style="float: right;"><?php echo $this->__("View All"); ?></a>
                </div>
            </div>
        </div>
        <script type="text/javascript">decorateGeneric($$('ul.news-list li'), ['odd', 'even', 'first', 'last'])</script>
    <?php endif; ?> 
    <?php
else:
    $url = Mage::getBaseUrl();
    Mage::app()->getFrontController()->getResponse()->setRedirect($url);
endif;
?>