<?php
    if (Mage::getStoreConfig('news/news_general/enabled') == 1):
        $i = 0;
        $collection = $this->getCachedCollection();
        $count = count($collection);
        if ($count !== 0):
        ?>
        <div class="block block-poll news-extra-block ">
            <div class="block-title">
                <strong><span><?php echo $this->__('Latest News');?></span></strong>
            </div>
            <div class="block-content">
                <marquee direction="up" id="scroll_news" scrollamount="2" height="80">
                    <ul class="news-list">
                        <?php foreach ($collection as $news_item): ?>
                            <li onMouseOver="document.getElementById('scroll_news').setAttribute('scrollamount', 0, 0);" OnMouseOut="document.getElementById('scroll_news').setAttribute('scrollamount', 2, 0);">
                                <label><a href="<?php echo $this->getUrl('news/index/view') . '?id=' . $news_item->getNewsId(); ?>">
                                    <?php echo $news_item->getTitle(); ?></a></label>
                            </li>
                            <?php endforeach; ?> 
                    </ul>
                </marquee>
                <div class="actions" >
                    <a href="<?php echo $this->getUrl('news/index') ?>" style="float: right;"><?php echo $this->__("View All"); ?></a>
                </div>
            </div>
        </div>
        <script type="text/javascript">decorateGeneric($$('ul.news-list li'), ['odd', 'even', 'first', 'last'])</script>
        <?php endif;
        endif;
?>