
<?php
    if (Mage::getStoreConfig('news/news_general/enabled')):
        $i = 0;
        $collection = $this->getCachedCollection();

        $count = count($collection);
        if ($count !== 0):
        ?>
	<!--
        <?php
            $breadcrumbs = $this->getLayout()->getBlock('breadcrumbs');
            $breadcrumbs->addCrumb('home', array('label' => Mage::helper('cms')->__('Home'), 'title' => Mage::helper('cms')->__('Home Page'), 'link' => Mage::getBaseUrl()));
            $breadcrumbs->addCrumb('News', array('label' => 'News', 'title' => 'News'));
            echo $this->getLayout()->getBlock('breadcrumbs')->toHtml();
        ?> -->
	<h2 style="font-size:2em;">PRESS</h2></br>
        <?php foreach ($collection as $news_item): ?>
            <div class="block news-block">
                <div class="block-title"><strong><span style="font-size:1.5em;"> <a href="<?php echo $this->getUrl('*/*/view') . '?id=' . $news_item->getNewsId(); ?>"><?php echo $news_item->getTitle(); ?></a></span></strong></div>
                <div class="block-content">
                    <?php echo $news_item->getIntro(); ?>
                    <a href="<?php echo $this->getUrl('*/*/view') . '?id=' . $news_item->getNewsId(); ?>" class="read-more"><?php echo $this->__('Read more') ?></a>
                    <div class="divider"></div>

                    <div class="publish-date">
			</br>
                      	<h5 style="font-size:1em;"> <?php echo $this->__('Publish Date:'); ?></h5>
                        <p><?php echo date("F j, Y", strtotime($news_item->getDateToPublish())); ?></p>
                    </div>


                    <?php if (Mage::getStoreConfig('news/news_general/share_on_socialmedia') == 1) : ?>
                        <div class="social-links">

                            <script type="text/javascript" src="https://ws.sharethis.com/button/buttons.js"></script>
                            <script type="text/javascript">stLight.options({publisher: "8453cbb3-3515-47cc-9e48-57c726813928", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>

                            <span class='st_facebook_hcount' displayText='Facebook' st_url="<?php echo $this->getUrl('*/*/view') . '?id=' . $news_item->getNewsId(); ?>"></span>
                            <span class='st_twitter_hcount' displayText='Tweet' st_url="<?php echo $this->getUrl('*/*/view') . '?id=' . $news_item->getNewsId(); ?>"></span>
                            <span class='st_linkedin_hcount' displayText='LinkedIn' st_url="<?php echo $this->getUrl('*/*/view') . '?id=' . $news_item->getNewsId(); ?>"></span>
                            <span class='st_fblike_hcount' displayText='Facebook Like' st_url="<?php echo $this->getUrl('*/*/view') . '?id=' . $news_item->getNewsId(); ?>"></span>
                        </div>
                        <?php endif; ?>

                </div>
<p>&nbsp;</p>
            </div>
            <?php endforeach; ?> 

        <?php echo $this->getChildHtml('Biztech_news_toolbar'); ?>
        <?php else: ?>
        <ul class="message"><li class="notice-msg"><span><?php echo $this->__('No News to publish.'); ?></span></li></ul>
        <?php endif; ?> 
    <?php
        else:
        $url = Mage::getBaseUrl();
        Mage::app()->getFrontController()->getResponse()->setRedirect($url);
        endif;
?>